# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About PI
    url: 'authors/daweizhang'
    weight: 10

  - name: Research
    url: 'research'
    weight: 20

  - name: People
    url: 'people'
    weight: 30

  - name: Publications
    url: 'publications'
    weight: 40

  - name: News
    url: 'news'
    weight: 50

  - name: Join Us
    url: 'join_us'
    weight: 50

  - name: Contact Us
    url: 'contact_us'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: Curriculum Vitae
#    url: uploads/leonelli_mauro.pdf
#    weight: 50
